; C:\vb\!sIRC\frmLoadProfile.frm.asm
; Generated by zConvert FRM2ASM 0.10
; Visit http://KomA.gulli.com for Updates and newer Versions!
; Please send bug reports (with FRM file) to bazik@x-mail.net

        .486
        .model flat, stdcall
        option casemap :none

        include \masm32\include\windows.inc
        include \masm32\include\user32.inc
        include \masm32\include\kernel32.inc
        include \masm32\include\gdi32.inc

        includelib \masm32\lib\user32.lib
        includelib \masm32\lib\kernel32.lib
        includelib \masm32\lib\gdi32.lib



		CHECKBOX1		equ 1
		BUTTON1		equ 2
		BUTTON2		equ 3
		BUTTON3		equ 4
		LISTBOX1		equ 5
		LABEL1		equ 6
		LABEL2		equ 7
.data


		szClassName		db "frmLoadProfile", 0

		wc		WNDCLASSEX <sizeof wc, CS_HREDRAW \
			or CS_VREDRAW or CS_BYTEALIGNWINDOW, \
			offset WndProc, 0, 0, 400000h, \
			0, 0, COLOR_BTNFACE + 1, 0, \
			offset szClassName, 0>

		szCheckBoxClass		db "BUTTON", 0
		szButtonClass		db "BUTTON", 0
		szListBoxClass		db "LISTBOX", 0
		szLabelClass		db "STATIC", 0


		szfrmLoadProfile		db "sIRC - Load Profile", 0
		szchkLoadAuto		db " Load this profile automatically from now on. ", 0
		szcmdDelete		db "&Delete", 0
		szcmdLoadProfile		db "&Load Profile", 0
		szcmdNewProfile		db "&New Profile...", 0
		szlblTitle		db "User Profiles", 0
		szLabel2		db "$"frmLoadProfile.frx":05EC", 0

.data?
		hWnd0001		 dd ?
		msg		MSG <?>
		hFont		dd ?
		hCheckBox0001		 dd ?
		hButton0001		 dd ?
		hButton0002		 dd ?
		hButton0003		 dd ?
		hListBox0001		 dd ?
		hLabel0001		 dd ?
		hLabel0002		 dd ?


      .code

  start:

      call WinMain
      invoke ExitProcess, eax

  WinMain proc
      mov wc.hIcon, 0
      invoke LoadCursor, 0, IDC_ARROW
      mov wc.hCursor, eax
      invoke RegisterClassEx, addr wc
      invoke GetSystemMetrics, SM_CXSCREEN
      mov esi,eax
      invoke GetSystemMetrics, SM_CYSCREEN
      shr esi, 1
      shr eax, 1
      sub eax, 296/2
      sub esi, 234/2

      invoke CreateWindowEx, WS_EX_TOPMOST,
                             addr szClassName,
                             addr szfrmLoadProfile,
                             WS_CAPTION or WS_MINIMIZEBOX or WS_SYSMENU or WS_VISIBLE,
                             esi, eax, 296, 234, 0, 0, 400000h, 0
      mov hWnd0001, eax
      invoke ShowWindow, hWnd0001, SW_SHOWNORMAL
      invoke UpdateWindow, hWnd0001
      mov esi, offset msg
   @@:
      invoke GetMessage, esi, 0, 0, 0
      or eax, eax
      je @F
      invoke TranslateMessage, esi
      invoke DispatchMessage, esi
      jmp @B
   @@:
      mov eax, msg.wParam
      ret
  WinMain endp

  WndProc proc hWin :DWORD,uMsg :DWORD, wParam :DWORD, lParam :DWORD

     .if uMsg == WM_CREATE
        invoke GetStockObject, DEFAULT_GUI_FONT
        mov hFont, eax

		invoke CreateWindowEx, 0, addr szCheckBoxClass, addr szchkLoadAuto, WS_CHILD or WS_VISIBLE or BS_AUTOCHECKBOX, 16, 144, 266, 15, hWin, CHECKBOX1, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdDelete, WS_CHILD or WS_VISIBLE, 230, 71, 60, 25, hWin, BUTTON1, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdLoadProfile, WS_CHILD or WS_VISIBLE, 202, 173, 88, 25, hWin, BUTTON2, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdNewProfile, WS_CHILD or WS_VISIBLE, 8, 173, 88, 25, hWin, BUTTON3, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, WS_EX_CLIENTEDGE, addr szListBoxClass, 0, WS_CHILD or WS_VISIBLE, 16, 71, 207, 67, hWin, LISTBOX1, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szLabelClass, addr szlblTitle, WS_CHILD or WS_VISIBLE, 24, 7, 71, 13, hWin, LABEL1, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szLabelClass, addr szLabel2, WS_CHILD or WS_VISIBLE, 17, 24, 287, 45, hWin, LABEL2, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0

    .elseif uMsg == WM_DESTROY

        invoke PostQuitMessage, 0
        xor eax, eax
        ret

    .endif

    invoke DefWindowProc, hWin, uMsg, wParam, lParam

    ret

WndProc endp

end start
