; C:\vb\!sIRC\frmOptions.frm.asm
; Generated by zConvert FRM2ASM 0.10
; Visit http://KomA.gulli.com for Updates and newer Versions!
; Please send bug reports (with FRM file) to bazik@x-mail.net

        .486
        .model flat, stdcall
        option casemap :none

        include \masm32\include\windows.inc
        include \masm32\include\user32.inc
        include \masm32\include\kernel32.inc
        include \masm32\include\gdi32.inc

        includelib \masm32\lib\user32.lib
        includelib \masm32\lib\kernel32.lib
        includelib \masm32\lib\gdi32.lib



		BUTTON1		equ 1
		BUTTON2		equ 2
		BUTTON3		equ 3
		BUTTON4		equ 4
		BUTTON5		equ 5
		BUTTON6		equ 6
		BUTTON7		equ 7
		LISTBOX1		equ 8
		BUTTON8		equ 9
		TEXTBOX1		equ 10
		LABEL1		equ 11
		LABEL2		equ 12
		LABEL3		equ 13
		FRAME1		equ 14
.data


		szClassName		db "frmOptions", 0

		wc		WNDCLASSEX <sizeof wc, CS_HREDRAW \
			or CS_VREDRAW or CS_BYTEALIGNWINDOW, \
			offset WndProc, 0, 0, 400000h, \
			0, 0, COLOR_BTNFACE + 1, 0, \
			offset szClassName, 0>

		szButtonClass		db "BUTTON", 0
		szListBoxClass		db "LISTBOX", 0
		szTextBoxClass		db "EDIT", 0
		szLabelClass		db "STATIC", 0
		szFrameClass		db "BUTTON", 0


		szfrmOptions		db "Options", 0
		szcmdApply		db "&Apply", 0
		szcmdCancel		db "&Cancel", 0
		szcmdOk		db "&Okay", 0
		szcmdScriptDown		db "6", 0
		szcmdScriptUp		db "5", 0
		szcmdRemoveScript		db "Remove", 0
		szcmdAddScript		db "Add", 0
		szcmdScriptDefFolder		db "...", 0
		sztxtDefScriptFolder		db "C:\apps\sIRC\", 0
		szlblEE1		db "", 0
		szlblSc		db "Loaded Scripts&:", 0
		szlblSF		db "Default Script Folder&:", 0
		szfrmTitle		db " Options ", 0

.data?
		hWnd0001		 dd ?
		msg		MSG <?>
		hFont		dd ?
		hButton0001		 dd ?
		hButton0002		 dd ?
		hButton0003		 dd ?
		hButton0004		 dd ?
		hButton0005		 dd ?
		hButton0006		 dd ?
		hButton0007		 dd ?
		hListBox0001		 dd ?
		hButton0008		 dd ?
		hTextBox0001		 dd ?
		hLabel0001		 dd ?
		hLabel0002		 dd ?
		hLabel0003		 dd ?
		hFrame0001		 dd ?


      .code

  start:

      call WinMain
      invoke ExitProcess, eax

  WinMain proc
      mov wc.hIcon, 0
      invoke LoadCursor, 0, IDC_ARROW
      mov wc.hCursor, eax
      invoke RegisterClassEx, addr wc
      invoke GetSystemMetrics, SM_CXSCREEN
      mov esi,eax
      invoke GetSystemMetrics, SM_CYSCREEN
      shr esi, 1
      shr eax, 1
      sub eax, 399/2
      sub esi, 360/2

      invoke CreateWindowEx, WS_EX_TOPMOST,
                             addr szClassName,
                             addr szfrmOptions,
                             WS_CAPTION or WS_MINIMIZEBOX or WS_SYSMENU or WS_VISIBLE,
                             esi, eax, 399, 360, 0, 0, 400000h, 0
      mov hWnd0001, eax
      invoke ShowWindow, hWnd0001, SW_SHOWNORMAL
      invoke UpdateWindow, hWnd0001
      mov esi, offset msg
   @@:
      invoke GetMessage, esi, 0, 0, 0
      or eax, eax
      je @F
      invoke TranslateMessage, esi
      invoke DispatchMessage, esi
      jmp @B
   @@:
      mov eax, msg.wParam
      ret
  WinMain endp

  WndProc proc hWin :DWORD,uMsg :DWORD, wParam :DWORD, lParam :DWORD

     .if uMsg == WM_CREATE
        invoke GetStockObject, DEFAULT_GUI_FONT
        mov hFont, eax

		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdApply, WS_CHILD or WS_VISIBLE, 290, 298, 54, 27, hWin, BUTTON1, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdCancel, WS_CHILD or WS_VISIBLE, 233, 298, 54, 27, hWin, BUTTON2, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdOk, WS_CHILD or WS_VISIBLE, 176, 298, 54, 27, hWin, BUTTON3, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdScriptDown, WS_CHILD or WS_VISIBLE, 204, 217, 22, 23, hWin, BUTTON4, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdScriptUp, WS_CHILD or WS_VISIBLE, 181, 217, 22, 23, hWin, BUTTON5, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdRemoveScript, WS_CHILD or WS_VISIBLE, 100, 217, 57, 23, hWin, BUTTON6, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdAddScript, WS_CHILD or WS_VISIBLE, 56, 217, 44, 23, hWin, BUTTON7, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, WS_EX_CLIENTEDGE, addr szListBoxClass, 0, WS_CHILD or WS_VISIBLE, 56, 80, 169, 134, hWin, LISTBOX1, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szButtonClass, addr szcmdScriptDefFolder, WS_CHILD or WS_VISIBLE, 207, 31, 18, 18, hWin, BUTTON8, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, WS_EX_CLIENTEDGE, addr szTextBoxClass, addr sztxtDefScriptFolder, WS_CHILD or WS_VISIBLE, 56, 29, 171, 21, hWin, TEXTBOX1, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szLabelClass, addr szlblEE1, WS_CHILD or WS_VISIBLE, 157, 217, 23, 23, hWin, LABEL1, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szLabelClass, addr szlblSc, WS_CHILD or WS_VISIBLE, 50, 63, 81, 21, hWin, LABEL2, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szLabelClass, addr szlblSF, WS_CHILD or WS_VISIBLE, 50, 12, 102, 13, hWin, LABEL3, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0
		invoke CreateWindowEx, 0, addr szFrameClass, addr szfrmTitle, WS_CHILD or WS_VISIBLE or BS_GROUPBOX, 116, 4, 278, 288, hWin, FRAME1, 400000h, 0
		invoke SendMessage, eax, WM_SETFONT, hFont, 0

    .elseif uMsg == WM_DESTROY

        invoke PostQuitMessage, 0
        xor eax, eax
        ret

    .endif

    invoke DefWindowProc, hWin, uMsg, wParam, lParam

    ret

WndProc endp

end start
